### ISSUE TITLE
NPM install returns ENOTFOUND error

### ISSUE THREAD

**Issue by ishanashams** [sanderblue/solar-system-threejs#25]
Hello, trying to run this project on my local computer.

returning an error when i enter "npm install"

npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to http://cpc-artifactory.sym.paas.silver.com:8081/artifactory/api/npm/NPM/clone-stats/-/clone-stats-0.0.1.tgz failed, reason: getaddrinfo ENOTFOUND cpc-artifactory.sym.paas.silver.com cpc-artifactory.sym.paas.silver.com:8081
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

Am i missing anything? Could you assist with how to run the site locally?

Thanks.

**Comment by sanderblue** [comment]
That error indicates your npm config is pointing to a private registry. You probably have an `.npmrc` file on your computer that has the registry config setting set to http://cpc-artifactory.sym.paas.silver.com... In order to get around this, you'll need to create a `.npmrc` file in the `solar-system-threejs` project directory and set the `registry` config like this:
```
registry="https://registry.npmjs.org/"
```
Then try to run `npm install` again. Hope this helps. 

More information on `.npmrc` can be read [here](https://docs.npmjs.com/files/npmrc) 😄
